theme = "solarized_dark"

[editor.soft-wrap]
enable = true

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal.g]
q = ":reflow"
