[[language]]
name = "email"
scope = "text.email"
roots = []
file-types = ["eml", "email"]
rulers = [72]
language-servers = [ "ltex-ls" ]
text-width = 72

[[language]]
name = "python"
rulers = [100]
text-width = 100
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

[[language]]
name = "markdown"
language-servers = [ "ltex-ls" ]
formatter = { command = "git", args = ["stripspace"] }
auto-format = true

[[language]]
name = "git-commit"
language-servers = [ "ltex-ls" ]
formatter = { command = "git", args = ["stripspace"] }
auto-format = true
