cwd_filter = [
  "/tmp/.*",
]

history_filter = [
  "^ .*",        # leading space = private
  "^aerc",
  "apt",
  "^atuin",
  "^b3sum",
  '(^|\|)\s*base64\b',
  "^bcp",
  "^brew",
  "^btm",
  "^cal$",
  "^cal -3$",
  "^cargo install",
  "^cargo install-update",
  "^cargo binstall",
  "^cargo up",
  "^cat",
  "^cd",
  "^chezmoi",
  "^chmod",
  "^choose",
  "^claude",
  "^cp",
  "^croc",
  "^curl",
  "^delta",
  "^dict",
  "^dig",
  "^docker ps",
  "^dog",
  "^doggo",
  "dnf",
  "^dua",
  "^duf",
  "^dust",
  "^fastfetch",
  "^fd",
  "^fg",
  "^ffprobe",
  "^git",
  "^glow",
  "^grep",
  '(^|\|)\s*head\b',
  '(--|\s)help\b',
  '\b-h\b',
  "^hexyl",
  "^hx",
  "^jaq",
  "jless",
  "^jj",
  "^(u)?just",
  "^k9s",
  "^kill",
  "^la",
  "^ls",
  "^lt",
  "^man",
  "^make",
  "^mkdir",
  "^mise",
  "^mosh",
  "^mpv",
  "^mv",
  "^numbat",
  "^nvim",
  "^open",
  "^oxipng",
  "pacman",
  "^paru",
  "^pass",
  "^pastel",
  "^pkill",
  "^poetry",
  "^presenterm",
  "pytest",
  "^rg",
  "^rm",
  "^ruff",
  "^ruplacer",
  "^rustup self",
  "^rustup update",
  "^scp",
  '(^|\|)\s*sort\b',
  "^ssh",
  "^sudoedit",
  "^sudo -i$",
  "^systemctl poweroff$",
  "^systemctl reboot$",
  "^tar",
  '(^|\|)\s*tail\b',
  "^tailscale",
  "^tldr",
  "^tmux",
  "^touch",
  "^tokei",
  "^tree",
  "^typos",
  "^typst",
  "^units",
  "^unzip",
  "^vim",
  '(^|\|)\s*wc\b',
  "^which",
  "^xh",
  "^yay",
  "^zathura",
  "^zellij",
  "^zola",
]

enter_accept = true
search_mode = "daemon-fuzzy"

[sync]
records = true

[daemon]
enabled = true
autostart = true
