theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 3

[[block]]
block = "load"
interval = 5 
format = "{1m}"

[[block]]
block = "net"
device = "wlp4s0"
ssid = true
signal_strength = true
speed_up = false
speed_down = false
hide_inactive = true
hide_missing = true

[[block]]
block = "net"
device = "enp0s31f6"
ip = true
speed_up = false
speed_down = false
hide_inactive = true
hide_missing = true

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"
device = "DisplayDevice"
driver = "upower"

[[block]]
block = "time"
interval = 60
format = "%a %m-%d %R"
